### ISSUE TITLE
快速输入编辑会崩溃

### ISSUE THREAD

**Issue by xinhui1209** [fcitx5-android/fcitx5-android#129] opened 2022-10-09 15:03 UTC
[https://wwi.lanzouy.com/iXOGP0dj423c](日志 蓝奏云) 如题

**Comment by Sinofine** [comment] 2022-10-09 15:06
@xinhui1209 log文件直接拖放到github输入栏就可以上传了

**Comment by xinhui1209** [comment] 2022-10-09 15:10
> @xinhui1209 log文件直接拖放到github输入栏就可以上传了
手机端 不好意思😂

**Comment by CoelacanthusHex** [comment] 2022-10-09 15:22
> > 手机端 不好意思😂

那上传到云剪贴板 https://pastebin.aosc.io/

**Comment by rocka** [comment] 2022-10-09 15:30
caused by https://github.com/fcitx5-android/fcitx5-android/commit/8e7d89c275e10c28c7ab3d233d7d1ef017d64911#diff-29b5ecbaa9f0fc78ca41dd09b1484a1c9f0c86a46e65e056d192aaeba96e95b9L47

https://github.com/fcitx5-android/fcitx5-android/blob/8e7d89c275e10c28c7ab3d233d7d1ef017d64911/app/src/main/java/org/fcitx/fcitx5/android/ui/main/settings/QuickPhraseEditFragment.kt#L47

since `QuickPhrase` is not `Parcelable`, but `Serializable`

https://github.com/fcitx5-android/fcitx5-android/blob/8e7d89c275e10c28c7ab3d233d7d1ef017d64911/app/src/main/java/org/fcitx/fcitx5/android/data/quickphrase/QuickPhrase.kt#L6

**Comment by rocka** [comment] 2022-10-09 15:38
should be fixed by 331ab71

**Closed by rocka** 2022-10-09 15:38 UTC
Labels: bug, component: app
