### ISSUE TITLE
add support for themed icon

### ISSUE THREAD

**Issue by long-crypto** [fcitx5-android/fcitx5-android#597] opened 2024-10-04 00:10 UTC
### 摘要 / Summary

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive themed icon

### 系统版本 / OS Version

Lineageos 21

### 应用版本 / App Version

latest

**Comment by rocka** [comment] 2024-10-04 02:04
duplicate of #418

**Closed** 2024-10-04 02:04 UTC
Labels: duplicate, enhancement
